"""Render ``reports/model_report.md`` from ``reports/metrics/model.json``."""

from __future__ import annotations

from typing import Any

METRICS = [
    ("pr_auc", "PR-AUC"),
    ("roc_auc", "ROC-AUC"),
    ("recall_at_precision", "Recall @ precision ≥ min"),
    ("brier", "Brier"),
    ("ece", "ECE"),
]


def _ci(m: dict[str, float]) -> str:
    return f"{m['value']:.3f} [{m['ci_low']:.3f}, {m['ci_high']:.3f}]"


def _metric_table(rows: dict[str, dict[str, Any]]) -> str:
    head = "| model | base rate | " + " | ".join(lbl for _, lbl in METRICS) + " |"
    lines = [head, "|" + "---|" * (len(METRICS) + 2)]
    for name, m in rows.items():
        cells = " | ".join(_ci(m[k]) for k, _ in METRICS)
        lines.append(f"| {name} | {m['base_rate']['value']:.3f} | {cells} |")
    return "\n".join(lines)


def _candidates_table(c: dict[str, Any], selected: str) -> str:
    lines = [
        "| model | CV PR-AUC per fold | CV mean | val PR-AUC [95% CI] | val base rate | features |",
        "|---|---|---|---|---|---|",
    ]
    for name, v in c.items():
        folds = ", ".join(f"{s:.3f}" for s in v["cv_pr_auc"])
        mark = " **(selected)**" if name == selected else ""
        lines.append(
            f"| {name}{mark} | {folds} | {v['cv_pr_auc_mean']:.3f} | {_ci(v['val']['pr_auc'])} | "
            f"{v['val']['base_rate']['value']:.3f} | {v['n_features']} |"
        )
    return "\n".join(lines)


def _policy_section(p: dict[str, Any]) -> str:
    budgets = "\n".join(
        f"| {b['budget']:.0%} ({b['inspected']} runs) | {b['caught']} of {b['failures']} "
        f"({b['caught_frac']:.0%}) | {b['random_caught_frac']:.0%} |"
        for b in p["budgets"]
    )
    sens = "\n".join(
        f"| {s['ratio']:g}:1 | {s['threshold']:.3f} | {s['inspected_frac']:.1%} | "
        f"{s['caught_frac']:.0%} | {s['cost_model']:.3f} | {s['cost_inspect_none']:.3f} | "
        f"{s['cost_inspect_all']:.3f} | {s['cost_random_same_budget']:.3f} | "
        f"{s['savings_vs_best_naive']:+.3f} |"
        for s in p["sensitivity"]
    )
    return (
        "### Inspection budget (ranking only, no threshold)\n\n"
        "| inspect riskiest | failures caught | random inspection catches |\n|---|---|---|\n"
        f"{budgets}\n\n"
        "### Cost-based policy and sensitivity\n\n"
        "Inspect a run when its calibrated probability ≥ cost of inspection / cost of a "
        "missed defect. Costs are per run, in relative units.\n\n"
        "| ratio | threshold | inspected | caught | model | inspect none | inspect all | "
        "random (same budget) | savings vs best naive |\n|---|---|---|---|---|---|---|---|---|\n"
        f"{sens}\n\n"
        f"**Assumptions.**\n{p['assumptions']}"
    )


def render_model_report(r: dict[str, Any]) -> str:
    """Return the Phase 2 model report as markdown."""
    best = r["selected_model"]
    pv = r["test"]["paired_vs_reference"]
    sp = r["split"]
    split_rows = "\n".join(
        f"| {k} | {v['start'][:10]} → {v['end'][:10]} | {v['rows']} | {v['failures']} | "
        f"{v['failures'] / v['rows']:.1%} |"
        for k, v in sp.items()
    )
    verdict = (
        "the CI excludes 0, so the selected model is better on this test window"
        if pv["ci_low"] > 0
        else "the CI includes 0, so **we cannot claim the selected model is better** "
        "than the simpler reference"
    )
    return (
        "\n\n".join(
            [
                "# Defect prediction: model report",
                "_Generated by `processlens train` from `reports/metrics/model.json`. "
                "Do not edit by hand._",
                f"Git SHA `{r['tags']['git_sha'][:10]}`, data SHA-256 "
                f"`{r['tags']['data_sha256'][:12]}`.",
                "## Protocol",
                r["protocol"],
                "## Time-ordered split",
                "| window | dates | runs | failures | failure rate |\n|---|---|---|---|---|\n"
                + split_rows,
                "## Model selection (train CV and validation; test untouched)",
                _candidates_table(r["candidates"], best),
                "## Test window (evaluated once)",
                "Point estimate with 95% bootstrap CI. Compare PR-AUC with the test base rate; "
                "a no-skill model scores the base rate.",
                _metric_table(r["test"]["metrics"]),
                f"**Paired bootstrap, PR-AUC {pv['model']} − {pv['reference']}:** "
                f"{pv['diff']:+.3f} [{pv['ci_low']:+.3f}, {pv['ci_high']:+.3f}]; "
                f"share of resamples where it is not better: {pv['p_a_not_better']:.2f}. "
                f"Here {verdict}.",
                f"Calibration: {r['calibration']} (Platt) fit on validation.",
                "![PR curve](figures/model_pr_curve.png)",
                "![calibration](figures/model_calibration.png)",
                "## Inspection policy (test window)",
                _policy_section(r["policy_test"]),
                "![gains](figures/model_gains.png)",
                "![cost sensitivity](figures/model_cost_sensitivity.png)",
                "## Sensors dropped (decided on train only)",
                f"{len(r['dropped_on_train'])} sensors dropped for > threshold missingness or zero "
                "variance in the training window.",
            ]
        )
        + "\n"
    )
