"""Render docs/RESUME_BULLETS.md and docs/INTERVIEW_NOTES.md from reports/metrics/*.json.

Every bracket in the resume templates is filled from code; copilot numbers stay marked
as pending until a live `make agent-eval` has written reports/metrics/agent.json.
Usage: uv run python scripts/render_resume.py
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from render_readme import load, pct

ROOT = Path(__file__).resolve().parents[1]
PENDING = "[pending live eval]"
BIG_EFFECT = 1.0  # "large effect" cut-off for the headline benchmark number


def facts() -> dict[str, Any]:
    """Collect every number the bullets and notes need."""
    a, m, b, r, g = (
        load("audit"),
        load("model"),
        load("benchmark"),
        load("rootcause"),
        load("agent"),
    )
    if not (a and m and b and r):
        raise SystemExit("Run `make all` first.")
    best = m["selected_model"]
    t = m["test"]["metrics"][f"{best}_calibrated"]
    b20 = next(x for x in m["policy_test"]["budgets"] if x["budget"] == 0.2)
    rows_big = [
        v
        for v in b["by_beta"]["cluster_hit@5"]
        if v["method"] == "consensus" and v["beta"] >= BIG_EFFECT
    ]
    hit_big = sum(v["mean"] * v["count"] for v in rows_big) / sum(v["count"] for v in rows_big)
    mde = b["mde"]["values"]["consensus"]
    reached = sorted({v for v in mde.values() if v is not None})
    missed = [k.replace("_", "-") for k, v in mde.items() if v is None]
    mde_txt = (
        " / ".join(f"{v:g}σ" for v in reached)
        + " for "
        + " and ".join(k for k, v in mde.items() if v is not None)
        + " faults"
        if reached
        else "no reachable effect"
    )
    if missed:
        mde_txt += f" ({', '.join(missed)} faults never reached the target)"
    f: dict[str, Any] = {
        "N": f"{a['shape']['rows']:,}",
        "S": a["shape"]["sensors"],
        "B": pct(a["label"]["base_rate"], 1),
        "X": f"{t['pr_auc']['value']:.3f}",
        "a": f"{t['pr_auc']['ci_low']:.3f}",
        "b": f"{t['pr_auc']['ci_high']:.3f}",
        "test_base": f"{t['base_rate']['value']:.3f}",
        "Y": pct(b20["caught_frac"]),
        "Z": pct(b20["budget"]),
        "M": b["n_scenarios"],
        "H": pct(hit_big),
        "E": f"{BIG_EFFECT:g}",
        "F": pct(b["null_false_alarms"]["any_strong"]),
        "F_q": pct(b["null_false_alarms"]["any_q_below_alpha"]),
        "MDE": mde_txt,
        "best": best.replace("_", " "),
        "paired": m["test"]["paired_vs_reference"],
        "segments": " / ".join(
            pct(s["fail_rate"], 1) for s in a["time"]["fail_rate_by_split_segment"]
        ),
        "n_clusters": r["n_clusters"],
        "sensors_rc": r["sensors_analysed"],
        "top": r["suspects"][0],
        "bm": b,
        "ece": m["test"]["metrics"],
    }
    if g:
        v1, v2 = g["versions"]["v1"]["summary"], g["versions"]["v2"]["summary"]
        f.update(
            {
                "V": pct(v2["numeric_faithfulness"]),
                "A": pct(v2["abstention_accuracy_null"]),
                "K": g["n_scenarios"],
                "D": f"{(v2['numeric_faithfulness'] - v1['numeric_faithfulness']) * 100:+.0f} "
                "pts faithfulness",
            }
        )
    else:
        f.update({"V": PENDING, "A": PENDING, "K": 40, "D": PENDING})
    return f


def bullets(f: dict[str, Any]) -> str:
    """The four resume bullets with every bracket filled."""
    return (
        "\n".join(
            [
                "# Resume bullets",
                "_Generated by `scripts/render_resume.py` from `reports/metrics/*.json`._",
                "",
                "**ProcessLens: Manufacturing Root-Cause Analyzer + LLM Copilot** | Python, pandas, "
                "scikit-learn, LightGBM, SHAP, statsmodels, MLflow, LangGraph, Gemini, FastAPI, Streamlit",
                "",
                f"- Built a leakage-safe defect-prediction pipeline on UCI SECOM ({f['N']} runs, "
                f"{f['S']} sensors, {f['B']} failure rate) with time-ordered validation and pandera data "
                f"contracts. Reached PR-AUC {f['X']} (95% CI {f['a']}–{f['b']}) vs a {f['test_base']} "
                f"base rate; ranking runs by risk catches {f['Y']} of failures while inspecting the "
                f"riskiest {f['Z']} of runs (random inspection: {f['Z']}).",
                f"- Designed a planted-fault benchmark over {f['M']} scenarios to validate root-cause "
                "ranking (Mann–Whitney + BH-FDR, stability selection, SHAP, correlated-sensor "
                f"clustering). Consensus ranking found {f['H']} of planted causes in the top 5 at "
                f"≥{f['E']}σ effect, with a {f['F']} false-alarm rate on null scenarios; documented a "
                f"minimum detectable effect of {f['MDE']}.",
                "- Built a LangGraph copilot that writes structured root-cause reports only from tool "
                f"outputs. A numeric verifier and abstention rules reached {f['V']} numeric faithfulness "
                f"and {f['A']} correct abstention across {f['K']} eval scenarios (prompt v2 vs v1: "
                f"{f['D']}). Served via FastAPI + Streamlit with drift monitoring and CI quality gates.",
                "",
                "> Wording note: the false-alarm figure is the share of no-cause scenarios with any "
                f"cluster graded *strong*; {f['F_q']} had at least one sensor with q < 0.05.",
            ]
        )
        + "\n"
    )


def notes(f: dict[str, Any]) -> str:
    """Two-minute walkthrough and answers to the eight prepared questions."""
    pv, bm, top = f["paired"], f["bm"], f["top"]
    nf = bm["null_false_alarms"]
    ov = bm["overall_by_method"]
    mde = bm["mde"]["values"]["consensus"]
    mde_txt = ", ".join(
        f"{k} " + ("not reached" if v is None else f"β = {v:g}") for k, v in mde.items()
    )
    qa = [
        (
            "Why PR-AUC and not accuracy or ROC-AUC on a 6.6% base rate?",
            f"Accuracy rewards predicting 'pass' for everything ({f['B']} failures). ROC-AUC is "
            "dominated by the many easy negatives and looks flattering. PR-AUC measures how clean "
            "the top of the ranking is, which is what an inspection team pays for, and its no-skill "
            f"level is the base rate: I report {f['X']} next to {f['test_base']}.",
        ),
        (
            "Why a time-ordered split? How did you prove there's no leakage?",
            f"The failure rate moves from {f['segments']} across train / validation / test, and "
            "sensors drift (see the PSI report), so a random split would let the model learn the "
            "future. Proof is in `tests/test_leakage.py`: strict timestamp order with no ties "
            "broken, imputer/scaler statistics equal to train-only statistics, corrupting test rows "
            "changes nothing that was fitted, a column that is all-missing in train is dropped even "
            "if test has values, and no feature can be the label or the timestamp.",
        ),
        (
            "Your PR-AUC is modest. Why is the project still useful?",
            f"Because I report it honestly: {f['best']} is not significantly better than logistic "
            f"regression (paired bootstrap {pv['diff']:+.3f}, CI {pv['ci_low']:+.3f} to "
            f"{pv['ci_high']:+.3f}). The ranking still catches {f['Y']} of failures in the riskiest "
            f"{f['Z']} of runs, roughly double random inspection. And the core contribution is "
            "the root-cause engine plus a benchmark that measures when it can and cannot be "
            "trusted.",
        ),
        (
            "How do you handle hundreds of highly correlated sensors? Why clusters?",
            f"I cluster on 1 − |Spearman ρ| ({f['sensors_rc']} sensors → {f['n_clusters']} "
            "clusters at ρ ≥ 0.8) and report suspects per cluster. Within a cluster the data "
            "cannot say which sensor matters; the benchmark shows this: the consensus ranks the "
            f"planted cluster in the top 5 in {pct(ov['consensus']['cluster_hit@5'])} of scenarios "
            f"but the exact sensor only {pct(ov['consensus']['sensor_hit@5'])}.",
        ),
        (
            "Can this prove causality?",
            "No. It is observational data; rankings are suspects associated with failure. The "
            "verifier even rejects causal phrasing in copilot reports. Confirmation needs process "
            "knowledge or a controlled trial; the recommended checks are designed for that.",
        ),
        (
            "How realistic is the planted-fault benchmark, and where could it mislead?",
            "It keeps the real sensor matrix, so missingness, correlation and drift are real; only "
            "the labels are synthetic. It can mislead because planted effects are additive and "
            "clean: no interactions, lags, label noise or unmeasured causes. So its numbers are an "
            f"upper bound. It already shows real weaknesses: minimum detectable effects are "
            f"{mde_txt}, and the consensus did not beat the univariate screen "
            f"({pct(ov['consensus']['cluster_hit@5'])} vs {pct(ov['univariate']['cluster_hit@5'])} "
            "cluster hit@5), which I report rather than tune away.",
        ),
        (
            "Why doesn't the LLM pick the root cause? How do you stop it inventing numbers?",
            "The statistics decide; the LLM explains. It only sees typed tool summaries, never raw "
            "rows. The abstain branch is decided in code from evidence grades. Every number in the "
            "report must cite a tool call and match its output (rounding-aware); free-text numbers "
            "must appear in the log; evidence grades cannot be upgraded; failures go back to a "
            "revise node at most twice. Tests include a deliberately wrong number that must be "
            "caught.",
        ),
        (
            "What would change in a real Michelin plant?",
            "Data volume and streaming (historian feeds, incremental drift checks), per-line or "
            "per-recipe windows, sensor metadata so clusters get physical names, engineers in the "
            "loop to label investigation outcomes, and a benchmark recalibrated on the plant's own "
            "data. The guardrails stay: contracts, leakage tests, measured limits, verified reports.",
        ),
    ]
    walk = (
        f'"I built a small version of the root-cause problem your process engineers solve, on '
        f"the public SECOM fab dataset: {f['N']} runs, {f['S']} sensors, {f['B']} failures. "
        "First, a leakage-safe prediction pipeline with time-ordered validation: PR-AUC "
        f"{f['X']} against a {f['test_base']} base rate, honestly modest, but inspecting the "
        f"riskiest {f['Z']} of runs catches {f['Y']} of failures. Second, a root-cause engine "
        "that combines Mann–Whitney with FDR control, stability selection and SHAP, and reports "
        f"clusters of correlated sensors; in the training window the top suspect is "
        f"`{top['representative']}` with {top['evidence']} evidence. Third, because real data "
        "has no ground truth, I planted known faults into the real sensor matrix: "
        f"{f['M']} scenarios. The consensus finds {f['H']} of planted causes in the top 5 at "
        f"effects of {f['E']} SD or more and raises a strong false alarm in "
        f"{pct(nf['any_strong'])} of no-cause scenarios; minimum detectable effect: "
        f"{f['MDE']}. Those limits are generated into the docs. Finally, a LangGraph copilot writes the "
        "engineer report only from tool outputs, with a verifier that traces every number and "
        'an abstain path when evidence is weak."'
    )
    parts = [
        "# Interview notes",
        "_Generated by `scripts/render_resume.py`; numbers come from `reports/metrics/*.json`._",
        "## Two-minute walkthrough",
        walk,
        "## Prepared questions",
    ]
    parts += [f"### {i}. {q}\n\n{a}" for i, (q, a) in enumerate(qa, start=1)]
    return "\n\n".join(parts) + "\n"


def main() -> None:
    f = facts()
    (ROOT / "docs" / "RESUME_BULLETS.md").write_text(bullets(f), encoding="utf-8")
    (ROOT / "docs" / "INTERVIEW_NOTES.md").write_text(notes(f), encoding="utf-8")
    print("Wrote docs/RESUME_BULLETS.md and docs/INTERVIEW_NOTES.md")


if __name__ == "__main__":
    main()
